apiVersion: v1
kind: Service
metadata:
  name: node-example
  labels:
    app: node-example
spec:
  selector:
    app: node-example
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 30007
  type: LoadBalancer